---
title: Experience AI Challenge | Stage 3 | Make a Machine Learning App
hero_image: images/banner.png
description: Create a machine learning model on Machine LEarning 4 Kids and code a Scratch application which uses it.
version: 4
listed: false
copyedit: false
last_tested: '2021-03-26'
steps:
- title: Introduction
- title: The Design Thinking Process
- title: Plan - Empathise, Define, Ideate
- title: Prototype your app
- title: Reflection
- title: Upgrade your project
- title: What next?
