---
title: invent-project-template
hero_image: images/banner.png
description: invent-project-template description
version: 4
listed: false
copyedit: false
last_tested: '2021-03-26'
steps:
- title: Introduction
- title: The Design Thinking Process
- title: Plan - Empathise, Define, Ideate
- title: Prototype your app
- title: Reflection
- title: Upgrade your project
- title: What next?
